from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, DecimalField, DateField, SelectField
from wtforms.validators import DataRequired, Length, NumberRange

class StockRequirementForm(FlaskForm):
    str_no = StringField('Stock Requirement Number', validators=[DataRequired(), Length(max=255)])
    str_date = DateField('Date', validators=[DataRequired()])
    shift = SelectField('Shift', choices=[('1', '1'), ('2', '2'), ('3', '3')], validators=[DataRequired()])
    incharge = StringField('Incharge', validators=[DataRequired(), Length(max=255)])
    req_raised_by = StringField('Requested By', validators=[DataRequired(), Length(max=255)])
    required_for = StringField('Required For', validators=[DataRequired(), Length(max=255)])
    material = StringField('Material', validators=[DataRequired(), Length(max=255)])
    material_quantity = IntegerField('Material Quantity', validators=[DataRequired()])
    amount_given = DecimalField('Amount Given', validators=[DataRequired()])
    vehicle_assigned = StringField('Vehicle Assigned', validators=[DataRequired(), Length(max=255)])
    vehicle_number = StringField('Vehicle Number', validators=[DataRequired(), Length(max=255)])
    driver_number = StringField('Driver Number', validators=[DataRequired(), Length(max=255)])

class StockOutwardForm(FlaskForm):
    required_for = StringField('Required For', validators=[DataRequired(), Length(max=255)])
    sales_type = StringField('Sales Type', validators=[DataRequired(), Length(max=255)])
    invoice_number = StringField('Invoice Number', validators=[DataRequired(), Length(max=255)])
    sr_no = StringField('SR Number', validators=[Length(max=255)])
    issued_by = StringField('Issued By', validators=[DataRequired(), Length(max=255)])
    party = StringField('Party', validators=[DataRequired(), Length(max=255)])
    vehicle_no = StringField('Vehicle Number', validators=[DataRequired(), Length(max=255)])
    material = StringField('Material', validators=[DataRequired(), Length(max=255)])
    rate = DecimalField('Rate', validators=[DataRequired()])
    quantity = IntegerField('Quantity', validators=[DataRequired()])
    gst = DecimalField('GST', validators=[DataRequired()])
    total_amount = DecimalField('Total Amount', validators=[DataRequired()])
    mod_of_payment = StringField('Mode of Payment', validators=[DataRequired(), Length(max=255)])
    amount_paid = DecimalField('Amount Paid', validators=[DataRequired()])
    balance = DecimalField('Balance', validators=[DataRequired()])
    driver_mobile = StringField('Driver Mobile', validators=[DataRequired(), Length(max=255)])
    owner_mobile = StringField('Owner Mobile', validators=[DataRequired(), Length(max=255)])

class StockInwardForm(FlaskForm):
    sti_no = StringField('STI Number', validators=[DataRequired(), Length(max=255)])
    date = DateField('Date', validators=[DataRequired()])
    shift = SelectField('Shift', choices=[('1', '1'), ('2', '2'), ('3', '3')], validators=[DataRequired()])
    incharge = StringField('Incharge', validators=[DataRequired(), Length(max=255)])
    referred_by = StringField('Referred By', validators=[Length(max=255)])
    required_for = StringField('Required For', validators=[DataRequired(), Length(max=255)])
    purchase_type = StringField('Purchase Type', validators=[DataRequired(), Length(max=255)])
    invoice_number = StringField('Invoice Number', validators=[DataRequired(), Length(max=255)])
    sr_no = StringField('SR Number', validators=[Length(max=255)])
    received_by = StringField('Received By', validators=[DataRequired(), Length(max=255)])
    purchase_party = StringField('Purchase Party', validators=[DataRequired(), Length(max=255)])
    vehicle_no = StringField('Vehicle Number', validators=[DataRequired(), Length(max=255)])
    material = StringField('Material', validators=[DataRequired(), Length(max=255)])
    rate = DecimalField('Rate', validators=[DataRequired()])
    mms_quantity = IntegerField('MMS Quantity', validators=[DataRequired()])
    mains_gross = DecimalField('Mains Gross', validators=[DataRequired()])
    mains_tare = DecimalField('Mains Tare', validators=[DataRequired()])
    mains_net_quantity = DecimalField('Mains Net Quantity', validators=[DataRequired()])
    gst = DecimalField('GST', validators=[DataRequired()])
    total_amount = DecimalField('Total Amount', validators=[DataRequired()])
    mod_of_payment = StringField('Mode of Payment', validators=[DataRequired(), Length(max=255)])
    amount_paid = DecimalField('Amount Paid', validators=[DataRequired()])
    balance = DecimalField('Balance', validators=[DataRequired()])
    driver_mobile = StringField('Driver Mobile', validators=[DataRequired(), Length(max=255)])
    driver_name = StringField('Driver Name', validators=[Length(max=255)])
    loading_site = StringField('Loading Site', validators=[Length(max=255)])
    unloading_site = StringField('Unloading Site', validators=[Length(max=255)])
    trip_amount = DecimalField('Trip Amount', validators=[DataRequired()])
    beta_allowance = DecimalField('Beta & Allowance', validators=[DataRequired()])
    total_d_amount = DecimalField('Total D Amount', validators=[DataRequired()])
    d_mode_of_payment = StringField('D Mode of Payment', validators=[DataRequired(), Length(max=255)])
    d_amount_paid = DecimalField('D Amount Paid', validators=[DataRequired()])
    d_balance = DecimalField('D Balance', validators=[DataRequired()])
    owner_mobile = StringField('Owner Mobile', validators=[DataRequired(), Length(max=255)])

class PaymentInwardForm(FlaskForm):
    voucher_number = StringField('Voucher Number', validators=[DataRequired(), Length(max=255)])
    date = DateField('Date', validators=[DataRequired()])
    shift = SelectField('Shift', choices=[('1', '1'), ('2', '2'), ('3', '3')], validators=[DataRequired()])
    incharge = StringField('Incharge', validators=[DataRequired(), Length(max=255)])
    referred_by = StringField('Referred By', validators=[Length(max=255)])
    sto_number = StringField('STO Number', validators=[DataRequired(), Length(max=255)])
    invoice_number = StringField('Invoice Number', validators=[DataRequired(), Length(max=255)])
    sales_type = StringField('Sales Type', validators=[DataRequired(), Length(max=255)])
    party_name = StringField('Party Name', validators=[DataRequired(), Length(max=255)])
    gst_number = StringField('GST Number', validators=[Length(max=255)])
    amount_paid = DecimalField('Amount Paid', validators=[DataRequired()])
    mode_of_payment = StringField('Mode of Payment', validators=[DataRequired(), Length(max=255)])
    payment_acknowledgement = StringField('Payment Acknowledgement', validators=[Length(max=255)])
    acknowledgement_number = StringField('Acknowledgement Number', validators=[Length(max=255)])

class PaymentOutwardForm(FlaskForm):
    voucher_number = StringField('Voucher Number', validators=[DataRequired(), Length(max=255)])
    date = DateField('Date', validators=[DataRequired()])
    shift = SelectField('Shift', choices=[('1', '1'), ('2', '2'), ('3', '3')], validators=[DataRequired()])
    incharge = StringField('Incharge', validators=[DataRequired(), Length(max=255)])
    referred_by = StringField('Referred By', validators=[Length(max=255)])
    sti_number = StringField('STI Number', validators=[DataRequired(), Length(max=255)])
    invoice_number = StringField('Invoice Number', validators=[DataRequired(), Length(max=255)])
    sales_type = StringField('Sales Type', validators=[DataRequired(), Length(max=255)])
    party_name = StringField('Party Name', validators=[DataRequired(), Length(max=255)])
    gst_number = StringField('GST Number', validators=[Length(max=255)])
    amount_paid = DecimalField('Amount Paid', validators=[DataRequired()])
    mode_of_payment = StringField('Mode of Payment', validators=[DataRequired(), Length(max=255)])
    payment_acknowledgement = StringField('Payment Acknowledgement', validators=[Length(max=255)])
    acknowledgement_number = StringField('Acknowledgement Number', validators=[Length(max=255)])