"""Added date to StockOutward

Revision ID: 55001830c11e
Revises: e7cc9c64adee
Create Date: 2024-05-13 16:59:42.527617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55001830c11e'
down_revision = 'e7cc9c64adee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_outward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_outward', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
